name: Merge to Production

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest


    steps:
        - name: Checkout branch
          uses: actions/checkout@v2

        - name: Configure committer
          run: git config --global user.name "Eric Saldivar"

        - name: Setup node
          uses: actions/setup-node@v1
          with:
            node-version: 16

        - name: Install from yarn lock file
          run: yarn install --frozen-lockfile

        - name: Run yarn release and update version
          run: yarn release